[package]
name = "aps"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.10.0"
le-stream = { version = "5.2.0", features = ["derive"], optional = true }
num-derive = "0.4.2"
num-traits = "0.2.19"

[features]
le-stream = ["le-stream/derive"]

[lints]
workspace = true
