[package]
name = "prototyping"
version = "0.1.0"
edition = "2024"

[dependencies]
zdp = { path = "../zdp" }
ezsp = { path = "../../ezsp" }
log = "0.4"
rand = "0.10.0-rc.5"
le-stream = { version = "5" }

[lints]
workspace = true
