[package]
name = "prototyping"
version = "0.1.0"
edition = "2024"

[dependencies]
zdp = { path = "../zdp" }
ezsp = { path = "../../ezsp" }
log = "0.4"
le-stream = { version = "5" }
macaddr = "1.0.1"
tokio = "1.48.0"

[lints]
workspace = true
