[package]
name = "zigbee-nwk"
version = "0.1.0"
edition = "2024"

[dependencies]
aps = { version = "0.1.0", path = "../aps" }
le-stream = "6.0.0"
log = "0.4.29"
macaddr = "1.0.1"
tokio = { version = "1.48.0", features = ["sync"] }
tokio-mpmc = "0.2.4"
zcl = { path = "../zcl" }
zdp = { path = "../zdp" }
zigbee = { path = "../zigbee" }

[lints]
workspace = true
