[package]
name = "zigbee-nwk"
version = "0.1.0"
edition = "2024"

[dependencies]
aps = { path = "../aps" }
le-stream = "6.0.0"
macaddr = "1.0.1"
zcl = { path = "../zcl" }
zigbee = { path = "../zigbee" }

[lints]
workspace = true
